CREATE TABLE TB_ROLES (
    ROLEID BIGINT NOT NULL AUTO_INCREMENT,
    ROLENAME VARCHAR(50) NOT NULL,
    description VARCHAR(255),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_TB_ROLES
        PRIMARY KEY (ROLEID),

    CONSTRAINT uk_tb_roles_role_name
        UNIQUE (ROLENAME)
);