CREATE TABLE TB_EMPLOYEES (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMPLOYEEID VARCHAR(20) NOT NULL UNIQUE,
    USERID BIGINT NOT NULL,
    FIRSTNAME VARCHAR(50) NOT NULL,
    LASTNAME VARCHAR(50),
    EMAIL VARCHAR(150) NOT NULL UNIQUE,
    PHONE VARCHAR(20),
    DEPARTMENTID BIGINT,
    DESIGNATIONID BIGINT,
    MANAGERID BIGINT,
    CLIENTID BIGINT,
    LOCATIONID BIGINT,
    JOININGDATE DATE,
    STATUS VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',

    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP
);