CREATE TABLE TB_PERMISSION (
    PERMISSIONID BIGINT NOT NULL AUTO_INCREMENT,
    PERMISSIONNAME VARCHAR(100) NOT NULL,
    description VARCHAR(255),
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_TB_PERMISSION
        PRIMARY KEY (PERMISSIONID),

    CONSTRAINT uk_tb_permissions_permission_name
        UNIQUE (PERMISSIONNAME)
);