CREATE TABLE TB_USERS (
    USERID BIGINT NOT NULL AUTO_INCREMENT,
    EMPLOYEEID VARCHAR(50) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    USEREMAIL VARCHAR(150) NOT NULL,
    USERPASSWORD VARCHAR(255) NOT NULL,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_by VARCHAR(100) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
        ON UPDATE CURRENT_TIMESTAMP,

    CONSTRAINT pk_TB_USERS
        PRIMARY KEY (USERID),

    CONSTRAINT uk_tb_users_username
        UNIQUE (USERNAME),

    CONSTRAINT uk_tb_users_email
        UNIQUE (USEREMAIL)
);