CREATE TABLE TB_USERROLES (
    USERID BIGINT NOT NULL,
    ROLEID BIGINT NOT NULL,

    CONSTRAINT pk_TB_USERROLES
        PRIMARY KEY (USERID, ROLEID),

    CONSTRAINT fk_tb_user_roles_user
        FOREIGN KEY (USERID)
        REFERENCES TB_USERS(USERID),

    CONSTRAINT fk_tb_user_roles_role
        FOREIGN KEY (ROLEID)
        REFERENCES TB_ROLES(ROLEID)
);