CREATE TABLE TB_ROLEPERMISSION (
    ROLEID BIGINT NOT NULL,
    PERMISSIONID BIGINT NOT NULL,

    CONSTRAINT pk_TB_ROLEPERMISSION
        PRIMARY KEY (ROLEID, PERMISSIONID),

    CONSTRAINT fk_tb_role_permissions_role
        FOREIGN KEY (ROLEID)
        REFERENCES TB_ROLES(ROLEID),

    CONSTRAINT fk_tb_role_permissions_permission
        FOREIGN KEY (PERMISSIONID)
        REFERENCES TB_PERMISSION(PERMISSIONID)
);