CREATE TABLE TB_REFRESHTOKENS (
    REFRESHTOKENSID BIGINT NOT NULL AUTO_INCREMENT,
    USERID BIGINT NOT NULL,
    token VARCHAR(500) NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_TB_REFRESHTOKENS
        PRIMARY KEY (REFRESHTOKENSID),

    CONSTRAINT uk_tb_refresh_tokens_token
        UNIQUE (token),

    CONSTRAINT fk_tb_refresh_tokens_user
        FOREIGN KEY (USERID)
        REFERENCES TB_USERS(USERID)
);